### ISSUE TITLE
MainWindow 被别的窗口挡在后面

### ISSUE THREAD

**Issue by Bowser1704** [jiangzc/CuteTranslation#1]
https://github.com/jiangzc/CuteTranslation/blob/df2bbd777a74abf59fd55f311d99af212b3ebfc4/src/mainwindow.cpp#L28

Window加上一个属性， 总在最前

**Comment by Bowser1704** [comment]
环境 Ubuntu 18.04

**Comment by jiangzc** [comment]
Confirmed and Fixed.
