### ISSUE TITLE
建议添加音标和翻译内容的复制按钮

### ISSUE THREAD

**Issue by jay763190097** [jiangzc/CuteTranslation#12]

**Comment by jiangzc** [comment]
这些都可以选中后手动复制。如果要添加按钮，我没有好的界面布局方案。

**Comment by jay763190097** [comment]
@jiangzc 双屏下选得选不中，字体和翻译不在一个屏幕上。感觉选不中，又不能复制，很难受。。。。

**Comment by jiangzc** [comment]
单词解释和音标复制的问题会在下一个版本中加入。
现在的只能复制段落（长文本）翻译的内容

**Comment by jiangzc** [comment]
之前用的是html   现在用QWidget 重写了一遍 ，QLabel可以设置成 selectable  然后就能复制了。这个在下一个版本中加入

**Comment by jiangzc** [comment]
![123](https://user-images.githubusercontent.com/13901512/87304990-530e8880-c548-11ea-9a89-30884d67a24b.png)

**Comment by jay763190097** [comment]
@jiangzc 欢迎新版出来解决多屏问题

**Comment by jiangzc** [comment]
后续版本( v0.5.0 )会在右上角加一个复制按钮

**Comment by jiangzc** [comment]
多屏问题已解决，新增复制按钮。 v0.4.2
