### ISSUE TITLE
安装后无法使用

### ISSUE THREAD

**Issue by snmin** [jiangzc/CuteTranslation#14]
安装完毕后启动软件正常，翻译时提示 ：
![image](https://user-images.githubusercontent.com/44972156/81820627-5ec9d880-9520-11ea-821b-8b4da3cf7223.png)
点击 lgnore 后弹出警告窗口，内容为白板，软件直接卡住无法关闭。

**Comment by jiangzc** [comment]
卡住无法关闭是Qt MessageBox的BUG，这个问题会在下一个版本改进。
baidu sdk error 表示翻译时返回错误码，建议重试。如果 baidu sdk error 问题复现，请提供Qt版本和Linux发行版版本

**Comment by snmin** [comment]
![image](https://user-images.githubusercontent.com/44972156/81823398-d0575600-9523-11ea-81e8-64d6daf535fb.png)

**Comment by snmin** [comment]
$ qmake -v
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory

**Comment by snmin** [comment]
一直是无法使用

**Comment by jiangzc** [comment]
问题在 deepin v20 beta 中复现，已标记为bug。

**Comment by jiangzc** [comment]
很有意思的BUG，最后发现是CPU速度太慢导致的，后面版本会修复，增加等待时间。
程序在调用nodejs获取token时，我限制了操作必须0.2秒内完成。
但是我的虚拟机和你的CPU速度太慢了，导致超时。
我把最大延时限制设置成2秒钟后解决。

**Comment by jiangzc** [comment]
已解决 -> v0.2.7  过几天发布

**Comment by jiangzc** [comment]
新版本已发布，试试看效果怎么样。

**Comment by snmin** [comment]
试了一下👌，唯一就是速度慢了一点。



发送自我的三星盖乐世智能手机。


-------- 原始信息 --------
发件人： jiangzc <notifications@github.com>
日期: 2020/5/14 10:02 (GMT+08:00)
收件人： jiangzc/CuteTranslation <CuteTranslation@noreply.github.com>
抄送： snmin <snminvip@outlook.com>, Author <author@noreply.github.com>
主题： Re: [jiangzc/CuteTranslation] 安装后无法使用 (#14)


新版本已发布，试试看效果怎么样。
