### ISSUE TITLE
manjaro下右键菜单退出后再打开软件显示多开自动关闭

### ISSUE THREAD

**Issue by codesssss** [jiangzc/CuteTranslation#16]

**Comment by codesssss** [comment]
貌似不太支持arch系 还是算了吧 谢谢作者

**Comment by jiangzc** [comment]
防止多开是通过文件互斥锁实现的，代码如下。
https://github.com/jiangzc/CuteTranslation/blob/f6725690ba7d69c02949542443eaaa89ef9200ac/src/main.cpp#L157-L169
