### ISSUE TITLE
请问大佬， archlinux有编译或安装步骤吗？

### ISSUE THREAD

**Issue by cossonleo** [jiangzc/CuteTranslation#19]
请问大佬， archlinux有编译或安装步骤吗？

**Comment by jiangzc** [comment]
编译要安装一些开发库，我也不清楚archlinux里面包的名字
安装的话，参考 install.sh 的内容

CuteTranslation v0.3.0  移除了WebEngine ，只需要这些依赖。问一下  @poemdistance   如何在 archlinux 下编译？

# Qt, Xlib
sudo apt install libxtst-dev libxcb-util0-dev build-essential
sudo apt install qt5-default libqt5x11extras5  libqt5x11extras5-dev

**Comment by cossonleo** [comment]
感谢大佬

**Comment by poemdistance** [comment]
@cossonleo

**Comment by poemdistance** [comment]
@cossonleo 
应该不用我了
