### ISSUE TITLE
不同系统中浏览器控件的字体不一样

### ISSUE THREAD

**Issue by Bowser1704** [jiangzc/CuteTranslation#2]
测试环境  deepin 15.11   Ubuntu 18.04

**Comment by jiangzc** [comment]
[interpret_js.html.zip](https://github.com/jiangzc/CuteTranslation/files/3824890/interpret_js.html.zip)

在Chrome中打开压缩包中的html文件，截图发一下。  
我这边的效果是  
![深度截图_选择区域_20191108221956](https://user-images.githubusercontent.com/13901512/68483130-f00c7980-0275-11ea-8caf-0be393e6f513.png)

**Comment by jiangzc** [comment]
可能要在html里指定字体

**Comment by jiangzc** [comment]
Fixed
