### ISSUE TITLE
[bug]百度sdk错误

### ISSUE THREAD

**Issue by cossonleo** [jiangzc/CuteTranslation#20]
![图片](https://user-images.githubusercontent.com/20379044/87494801-86553280-c682-11ea-98ec-eeca5a2098e9.png)

**Comment by jiangzc** [comment]
看看日志   ~/.local/share/Cute...

**Comment by cossonleo** [comment]
![图片](https://user-images.githubusercontent.com/20379044/87515456-70f5fd80-c6ae-11ea-9de6-300030f81ad9.png)
@jiangzc

**Comment by jiangzc** [comment]
你安装了 nodejs 吗， 终端执行 nodejs /opt/CuteTranslation/baidu.js aaa bbb    输出是什么？

**Comment by jiangzc** [comment]
这一段代码的问题，你可以单独把这个函数拿出来调试

https://github.com/jiangzc/CuteTranslation/blob/69b49145c286b01370954dfb3a6de7f59d328397/src/baidutranslate.cpp#L122-L140

**Comment by cossonleo** [comment]
感谢大佬，问题已经解决了
