### ISSUE TITLE
开发者可不可以提供arch的包，（建议aur）

### ISSUE THREAD

**Issue by Jontyshaw** [jiangzc/CuteTranslation#24]

**Comment by jiangzc** [comment]
#21   
我不会 archLinux ，Readme里有编译说明

**Comment by jiangzc** [comment]
@cossonleo   有没有志愿者帮忙， 维护arch的软件包呢？

**Comment by cossonleo** [comment]
> @cossonleo 有没有志愿者帮忙， 维护arch的软件包呢？
忙完这一阵，我研究一下

**Comment by cossonleo** [comment]
> @cossonleo 有没有志愿者帮忙， 维护arch的软件包呢？

忙完这一阵，我研究一下

**Comment by jiangzc** [comment]
https://aur.archlinux.org/packages/cutetranslation/
