### ISSUE TITLE
能否增加rekols词典中的网络定义

### ISSUE THREAD

**Issue by jay763190097** [jiangzc/CuteTranslation#28]
![图片](https://user-images.githubusercontent.com/16317178/92759405-47add100-f3c2-11ea-8e39-59b6ca2c8558.png)
如果把rekols的功能和界面效果加到cutetranslation就很完美了。

**Comment by jiangzc** [comment]
软件不需要也不适合加入这个功能。

**Comment by jay763190097** [comment]
@jiangzc v0.4.3版已经很棒了。双屏问题解决了，也更美观了，也能复制了。上面我提到的是增加固定搭配的词组显示，其实还是用的蛮多的
