### ISSUE TITLE
右键 FloatBtn 不要在xxx显示，功能无效

### ISSUE THREAD

**Issue by Bowser1704** [jiangzc/CuteTranslation#3]
Ubuntu 18.04   qt-default 编译

**Comment by jiangzc** [comment]
我这边 Qt version 5.7.1  会出现BUG，Qt 5.13.0 正常。问题已确认

**Comment by jiangzc** [comment]
已修改，但还需要进一步测试

https://github.com/jiangzc/CuteTranslation/blob/51a7d27881b3b8f3b71a7a35cef6c03502f72958/src/floatbutton.cpp#L53-L67
