### ISSUE TITLE
Host requires authentication

### ISSUE THREAD

**Issue by zsStrike** [jiangzc/CuteTranslation#32]
What's wrong with this case?
![image](https://user-images.githubusercontent.com/32895764/102991667-a56ebf00-4554-11eb-8e2b-829fa628dd9f.png)

**Comment by jiangzc** [comment]
Please upload your log   ~/.local/share/CuteTranslation/log.txt

**Comment by zsStrike** [comment]
It may be because I use the old software. After upgrade the cutetranslation, the software work nicely!
