### ISSUE TITLE
取词翻译时干掉多余的换行

### ISSUE THREAD

**Issue by zerofancy** [jiangzc/CuteTranslation#34]
在pdf中复制文本会有多余的空行，此时翻译结果往往会与实际相差甚远。希望提供个选项干掉这些空行，比如对于英文来说，真正段落结束处往往是个完整的句子，应该会以句号或冒号结尾。

（以下示例pdf来自谷歌学术）

[421425.pdf](https://github.com/jiangzc/CuteTranslation/files/6328840/421425.pdf)

**Comment by jiangzc** [comment]
参考 Readme 文档中“翻译界面附加功能”

换行处理可以忽略文本中的换行符。在某些软件如PDF阅读器中，如果直接选中以下段落翻译，效果会很差。这时点击翻译界面的N按钮，重新选中段落翻译，可以优化翻译效果。
> The Python installers for the Windows platform usually
include the entire standard library and often also include
many additional components. For Unix-like operating systems
Python is normally provided as a collection of packages,
so it may be necessary to use the packaging tools provided
with the operating system to obtain some or all of the optional components.

**Comment by jiangzc** [comment]
这个功能在翻译界面的右上角 靠左边的 “N” 图标

**Comment by zerofancy** [comment]
> 这个功能在翻译界面的右上角 靠左边的 “N” 图标

Thanks.
