### ISSUE TITLE
UOS专业版1041+鲲鹏920上使用出现获取OCR token失败

### ISSUE THREAD

**Issue by run4live** [jiangzc/CuteTranslation#41]
UOS专业版1041+鲲鹏920上使用出现获取OCR token失败

**Comment by jiangzc** [comment]
我重启了服务器，现在应该正常了

http://67.216.199.87:5000/token

**Comment by run4live** [comment]
非常感谢你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年12月28日(周二) 中午12:13
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [jiangzc/CuteTranslation] UOS专业版1041+鲲鹏920上使用出现获取OCR token失败 (Issue #41)




 
我重启了服务器，现在应该正常了
 
http://67.216.199.87:5000/token
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by run4live** [comment]
已经能够正常使用了。今天早上才看到邮箱里的信息，回复迟了，抱歉。
