### ISSUE TITLE
text：baidu sdk error 如何解决

### ISSUE THREAD

**Issue by rengui01** [jiangzc/CuteTranslation#42]

**Comment by rengui01** [comment]
刚刚退出i重新打开它就好了，请问是什么原因导致的这个问题，我应如何规避

**Comment by rengui01** [comment]
> _No description provided._

**Comment by rengui01** [comment]
这两天用了，发现这个错误会在识别不出单词的时候出现，但是我遇到这个错误的时候操作是正确的

**Comment by rengui01** [comment]
> 这两天用了，发现这个错误会在识别不出单词的时候出现，但是我遇到这个错误的时候操作是正确的

出现这个报错时我的操作是，按下 alt+q 它就直接弹出这个 text：baidu sdk error ，我都还没有开始识别

**Comment by jiangzc** [comment]
能提供软件日志吗？  
 ~/.local/share/CuteTranslation/log.txt

**Comment by rengui01** [comment]
[log.txt](https://github.com/jiangzc/CuteTranslation/files/7872950/log.txt)

**Comment by rengui01** [comment]
> 
[log.txt](https://github.com/jiangzc/CuteTranslation/files/7872955/log.txt)
